### ISSUE TITLE
[DEV] Boot2Snow: Entering longmode

### ISSUE THREAD

**Issue by ANEP-ET** [SnowFlakeOS/SnowFlake#3]
Crash after enable_long_mode function. 
It seems that setup_paging is not set up correctly at the pointer, or the page table is not initialized.

**Comment by ANEP-ET** [comment]
I found a solution.
This is resolved by changing the default syntax to Intel Syntax on Inline Assembly.

Add it to inline assembly block.
`.intel_syntax noprefix`

**Comment by xuserwhat** [comment]
@xuserwhat 문법 틀렸네요

**Comment by xuserwhat** [comment]
@xuserwhat * Add it to inline assembly block.

**Comment by snowbear1472** [comment]
@xuserwhat 문법이 참
